### ISSUE TITLE
out of bounds

### ISSUE THREAD

**Issue by maddin200** [foxBMS/foxbms-2#16]
src/app/driver/afe/nxp/mc33775a/nxp_mc33775a.c line 549
Code:
     uint16_t uid[3u]                          = {0};
    ...
    for (uint8_t j = 0u; j <= 3u; j++) {
                n775_state->n775Data.uid[n775_state->currentString][i - 1u] |= ((uint64_t)uid[j]) << (16u * j); // uid[j] out of bounds
            }

**Comment by foxBMS** [comment]
Hi @maddin200,

many thanks for the hint, we will have a look.

Best regards,
The foxBMS Team

**Comment by foxBMS** [comment]
Hi @maddin200,

We verified the behavior and the next release will include a fix for this.

Thanks for the hint!

Best regards,
The foxBMS Team

**Comment by foxBMS** [comment]
Hi @maddin200,

The issue has been fixed in foxBMS 2 v1.7.0.

Thanks again for the hint!

Best regards,
The foxBMS Team
