### ISSUE TITLE
identical expression

### ISSUE THREAD

**Issue by maddin200** [foxBMS/foxbms-2#17]
src/app/driver/can/can.c line 270
Code:
  canREG1->CTL = (uint32)0x00000000U | (uint32)0x00000000U /* <-- identical */  | (uint32)((uint32)0x0000000AU << 10U) |
                   (uint32)0x00020043U;

**Comment by foxBMS** [comment]
Hi @maddin200,

Thanks for pointing us at this.
However, this is part of auto-generated code (based on the HALCoGen configuration), and we therefore prefer to not alter it as long as the auto-generated code is valid and correct.

Best regards,
The foxBMS Team
