### ISSUE TITLE
No flashing capabilities?

### ISSUE THREAD

**Issue by taijisugiyama** [foxBMS/foxbms-2#18]
In foxbms 1 master, you could directly flash the binary code on the MCU without any debugger. Is there a similar case for foxbms 2 as well? As far as I can see, the only way to download the code onto the master board is to use an expensive debugger.

**Comment by foxBMS** [comment]
Dear @taijisugiyama,

we do currently only support flashing the binary onto the MCU via debugger (we are using Lauterbach debuggers, see https://docs.foxbms.org/tools/debugger/debugger-lauterbach.html). As a debugger is basically always needed when developing, we chose to make a debugger a requirement for development.

Best regards,
The foxBMS Team
