### ISSUE TITLE
Cell Voltage Transmission Code Fix

### ISSUE THREAD

**Issue by colookie** [foxBMS/foxbms-2#2]
Hello, there is an issue in lines 76 & 77 of the can_cbs_tx_voltage.c file, particularly regarding the start bits. Cell voltage 2 has the start bit for cell voltage 3 and cell voltage 3 overwrites cell voltage 0. The correct start bits to correctly line up with the dbc file are 11, 30, 33, 52.

**Comment by foxBMS** [comment]
Dear @colookie,

Thanks for pointing us to this.

Your are absolutely correct, the current implementation is wrong and your solution is correct.
We have fixed this already in our development branch and the fix will be available in the next release.

Best regards,
The foxBMS Team

**Comment by foxBMS** [comment]
Dear @colookie,

we have published [v1.1.1](https://github.com/foxBMS/foxbms-2/releases/tag/v1.1.1) that includes the fix for this bug.

Best regards,
The foxBMS Team
