### ISSUE TITLE
Manufacturing FoxBMS master

### ISSUE THREAD

**Issue by taijisugiyama** [foxBMS/foxbms-2#22]
Greetings FoxBMS ppl,

I would like to know if there is a PCB manufacturer recommended by FoxBMS (in germany). I am trying to get the foxbms master manufactured for a project but the manufacturer I know seems to be taking too long (14 weeks+). I would be very grateful for the recommendation. Thank you for your time!

**Comment by luiginoschese** [comment]
Hello, i has some slaves manufactured by EuroCircuits, I suppose the master could also be manufactured by them.
