### ISSUE TITLE
Wrong value set in fram.c at line 127

### ISSUE THREAD

**Issue by God-of-platypus** [foxBMS/foxbms-2#26]
When there is an error with FRAM_WriteData function in the function FRAM_ReinitializeAllEntries, the variable ret_val is set to STD_OK.
The value should be STD_NOT_OK.

https://github.com/foxBMS/foxbms-2/blob/06d3878f26d05e3a7fc42e64af821664eb309e13/src/app/driver/fram/fram.c#L127

**Comment by foxBMS** [comment]
Dear @God-of-platypus,

Thanks for the report.
Yes this is a bug. We will fix this in the next release.

Best regards,
The foxBMS Team

**Comment by foxBMS** [comment]
Hi @God-of-platypus,

The issue has been fixed in foxBMS 2 v1.7.0.

Thanks for the hint!

Best regards,
The foxBMS Team
