### ISSUE TITLE
gui.bat not working

### ISSUE THREAD

**Issue by God-of-platypus** [foxBMS/foxbms-2#28]
Hello,

When I try to run `.\tools\gui\gui.bat`, the program is able to find which pcan I am using.
But then it just stop. It seem to failed when it's trying to do the first check on baud_rate at line 84 of foxbms_gui.py.

**Comment by God-of-platypus** [comment]
After further searching the problem seems to be coming from the wx librarie

**Comment by foxBMS** [comment]
Dear @God-of-platypus,

> When I try to run `.\tools\gui\gui.bat`, the program is able to find which pcan I am using. But then it just stop. It seem to failed when it's trying to do the first check on baud_rate at line 84 of foxbms_gui.py.

What does exactly stop? Do you see this startup frame?

![image](https://github.com/foxBMS/foxbms-2/assets/24648128/e41745f6-53ee-4111-a43c-4f58297d14be)


> After further searching the problem seems to be coming from the wx librarie

Please provide a clear description what you did and what error messages you see.

The best way to get the full error log is, to **not** open the GUI by double clicking ``gui.bat`` in the File Explorer, but running ``gui.bat`` from ``cmd.exe``.

Best regards,
The foxBMS Team

**Comment by God-of-platypus** [comment]
I run the program from the vscode terminal.
I don't get an error message. It just stop after selecting which can device I am using.

**Comment by God-of-platypus** [comment]
And nothing is opening from our side

**Comment by God-of-platypus** [comment]
The version wx that we have is the 4.2.1

**Comment by God-of-platypus** [comment]
Here's what we get if we harcode the baudrate:
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\github\foxbms-2-master\foxbms-2-master\tools\gui\fgui\__main__.py", line 45, in <module>
    foxbms_gui.main()  # pylint: disable=no-value-for-parameter
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\github\foxbms-2-master\foxbms-2-master\tools\gui\fgui\foxbms_gui.py", line 106, in main
    EntryFrame(can_process=can_process)
  File "D:\github\foxbms-2-master\foxbms-2-master\tools\gui\fgui\entry\entry_frame.py", line 75, in __init__
    self.initialize_gui()
  File "D:\github\foxbms-2-master\foxbms-2-master\tools\gui\fgui\entry\entry_frame.py", line 106, in initialize_gui
    self.SetIcon(get_icon())
  File "D:\github\foxbms-2-master\foxbms-2-master\tools\gui\fgui\misc\gui_helpers.py", line 79, in get_icon
    logo_img = wx.Image(logo_foxbms.GetImage())
  File "C:\Users\User\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\wx\lib\embeddedimage.py", line 64, in GetImage
    return wx.Image(stream)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by God-of-platypus** [comment]
I was able to fix it by replacing the GetImage function in ~\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\wx\lib\embeddedimage.py by 
```python 
def GetImage(self):
        stream = BytesIO(self.GetData())
        locale = wx.Locale(wx.LANGUAGE_ENGLISH)
        return wx.Image(stream)
```

**Comment by foxBMS** [comment]
Thanks for the log. What are your Windows locale settings? Can you please provide the output of ``locale.getlocale()`` from the conda environment your trying to run the GUI from?

> I was able to fix it by replacing the GetImage function in ~\miniconda3\envs\2023-02-fennec-fox\lib\site-packages\wx\lib\embeddedimage.py by
> 
> ```python
> def GetImage(self):
>         stream = BytesIO(self.GetData())
>         locale = wx.Locale(wx.LANGUAGE_ENGLISH)
>         return wx.Image(stream)
> ```

Ok, thanks good to hear, that you can work around the issue. However, we try to implement a solution that does not need to change the `wxPython` installation, since this is not clean solution.

**Comment by God-of-platypus** [comment]
I was able to use the same version of wxpython as you. And the command return ```language: 1
Name: en```

**Comment by foxBMS** [comment]
> I was able to use the same version of wxpython as you. And the command return `language: 1 Name: en`


So does it now work for you? If so, what changes did you implement?

**Comment by God-of-platypus** [comment]
I added the following line to the GetImage function: locale = wx.Locale(wx.LANGUAGE_ENGLISH)

**Comment by foxBMS** [comment]
Thanks.

However, this is not a solution that is broadly applicable and maybe even hinders other programs to work as intended, we do not consider this a reasonable workaround.
We keep this issue open, to see if this issue rises more often.

**Comment by sankadiaji** [comment]
gui.bat not working

**Comment by foxBMS** [comment]
Dear @God-of-platypus,

could you please test whether the solution in https://github.com/foxBMS/foxbms-2/issues/38#issuecomment-2009203841 also fixes your problem (assuming you revert the change you implemented in `GetImage` etc.)?
