### ISSUE TITLE
wrong version in WAF?

### ISSUE THREAD

**Issue by erniemaster** [foxBMS/foxbms-2#3]
Hello foxBMS-team,

for some projects i searched for an open-source-BMS and found this awesome work. After getting familiar with the docs and the toolchain i tried to build the application, but encounteres some problems. After following the setup descripted in the docs i can't build the application, just getting an error message:

`Build failed
Traceback (most recent call last):
  File "E:\01_Repos\07_FoxBMS\tools\waf3-2.0.22-1241519b19b496207abef1f72bbf61c2\waflib\Task.py", line 180, in process
    ret=self.run()
  File "E:\01_Repos\07_FoxBMS\tools\waf-tools\f_ti_arm_cgt.py", line 1172, in run
    self.generator.bld.fatal(
  File "E:\01_Repos\07_FoxBMS\tools\waf3-2.0.22-1241519b19b496207abef1f72bbf61c2\waflib\Context.py", line 261, in fatal
    raise self.errors.ConfigurationError(msg,ex=ex)
waflib.Errors.ConfigurationError: Extracted version from git repo (1.1.0) does not match version defined in waf (1.1.1).`

after going back to the version 1.1.0 i'm able to build the binaries.
Probably there is a small typo in some configs or scripts for WAF?

Kind regards.

**Comment by foxBMS** [comment]
Dear @erniemaster,

this should not happen. Could you please run

    git log --graph --decorate --pretty=oneline --abbrev-commit --all

in your copy of the repository and paste the output here?

Best regards,
The foxBMS Team

**Comment by erniemaster** [comment]
@foxBMS 

of course, here is my output:
`* 329216a (HEAD -> master, origin/master, origin/HEAD) Bugfix release of foxBMS 2 (v1.1.1)
* aa1ce62 (tag: v1.1.0) Minor release of foxBMS 2 (v1.1.0)
* 9fff1ab (tag: v1.0.2) Bugfix release of foxBMS 2 (v1.0.2)
* adcaf20 (tag: v1.0.1) Bugfix release of foxBMS 2 (v1.0.1)
* 62288b3 (tag: v1.0.0) Initial commit of foxBMS 2 (v1.0.0)`

**Comment by foxBMS** [comment]
Dear @erniemaster,

Thanks, this seems fine.
- Have you tried to re-configure the project, i.e. running ``waf configure`` again before running the build command?
- Have you tried to build from a clean repository state?


Best regards,
The foxBMS Team

**Comment by erniemaster** [comment]
Dear @foxBMS 

rerunning `waf configure` havn't solved my problem, but starting from scratch (again) as you mentioned resolved the problem.
it seems that there was something messed up with my fork of the repo... i used sourcetree do download the files, probably this has lead to this unexpected behavior...

Awesome help, thanks a lot!!!

if it's okay, i have one more question:
besides the software i also need the hardware, but in the folder "hardware" there's only a readme, which points to a zip-file containing the schematics as a pdf. Is the altium project also open source like version 1?
