### ISSUE TITLE
Difference between variants

### ISSUE THREAD

**Issue by taijisugiyama** [foxBMS/foxbms-2#33]
Hello! 
Can someone please tell me what is the difference between Foxbms master variants? I by mistake ordered the production variant. Does that make any difference? Would it still work as intended? Thank you so much for the help.

**Comment by foxBMS** [comment]
Dear @taijisugiyama,

The foxBMS variants are used to configure the population of specific parts. You used the correct variant. We are ourselves producing according to variant "production".

Best regards,
The foxBMS Team
