### ISSUE TITLE
Programming the SBC chip results in smoke

### ISSUE THREAD

**Issue by taijisugiyama** [foxBMS/foxbms-2#35]
Greetings,

So I am running the SBC chip in emulated mode with the voltages written in the schematic of the master board. When I remove the debug pin, the part BUK9K13-60EX sizzles and some smoke comes out. After that I am thrown out of test mode from Flexgui. I don't really understand what could be the issue.

**Comment by foxBMS** [comment]
Dear @BhavaySen,

You can find the OTP files at https://iisb-foxbms.iisb.fraunhofer.de/foxbms/gen2/hardware/release/.
Please ensure to read and understand the information in `NOTICE.txt` which is included in the .zip file.

Please note that we provide support only for foxBMS boards manufactured and tested by us.
Please use the Issue tracker for bugs and for any technical questions, please reach out to us through [info@foxbms.org](mailto:info@foxbms.org).

Best regards,
The foxBMS Team
