### ISSUE TITLE
in continuation to Issue no. 36.

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#37]
[Issue No. 36 ](https://github.com/foxBMS/foxbms-2/issues/36#issuecomment-1943956723)

Thanks for the reply, Team foxBMS. However, I noticed that the [documentation](https://docs.foxbms.org/hardware/master/ti-tms570lc4357-vx.x.x/ti-tms570lc4357-v1.1.1.html#master-tms570-v1-1-1) you attached (documentation) does not mention anything about the Ignition signal. I found a section in the documentation ([SBC SECTION 4.34](https://docs.foxbms.org/software/modules/driver/sbc/sbc.html#module-files)) which mentions the requirement for an Ignition signal, but it does not specify the rating of the signal. I believe this information should be included in the Electrical Connection section. while as I asked the query regarding the powering up the MCU with PMIC without the INIT_FS commands. 

Just imagine, Processor is not programmed yet and the PMICs are programmed with the OTP. but in the state machine diagram there is a point where we have to write INIT_FS registers to power up the IC otherwise it will reset in 256uS window. Now, without the power   I cannot program the processor and the PMIC is not starting because it is not getting the INIT_FS values.

I am looking forward to your response.

Best Regards,
Bhavay Sen

**Comment by foxBMS** [comment]
Dear @BhavaySen,

If this is a continuation of #36, then please discuss your question there (whether it is closed or not).

Best regards,
The foxBMS Team.
