### ISSUE TITLE
CAN not working with the master

### ISSUE THREAD

**Issue by taijisugiyama** [foxBMS/foxbms-2#39]
Greetings,
Thank you for your continuous help. Whenever I try to run CAN with foxgui, it seems to give me this error. I have checked the CAN connections and everything seems to be fine. 

DEBUG:root:Logging level: DEBUG
INFO:root:Checking for pcan in ['PCAN_USBBUS1', 'PCAN_USBBUS2', 'PCAN_USBBUS3', 'PCAN_USBBUS4', 'PCAN_USBBUS5', 'PCAN_USBBUS6', 'PCAN_USBBUS7', 'PCAN_USBBUS8', 'PCAN_USBBUS9', 'PCAN_USBBUS10', 'PCAN_USBBUS11', 'PCAN_USBBUS12', 'PCAN_USBBUS13', 'PCAN_USBBUS14', 'PCAN_USBBUS15', 'PCAN_USBBUS16']
DEBUG:root:Checking PCAN_USBBUS1 (0)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS1', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS2 (1)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS2', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS3 (2)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS3', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS4 (3)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS4', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS5 (4)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS5', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS6 (5)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS6', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS7 (6)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS7', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS8 (7)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS8', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS9 (8)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS9', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS10 (9)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS10', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS11 (10)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS11', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS12 (11)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS12', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS13 (12)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS13', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS14 (13)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS14', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS15 (14)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS15', 'interface': 'pcan'}
DEBUG:root:Checking PCAN_USBBUS16 (15)
DEBUG:can:can config: {'state': <BusState.ACTIVE: 1>, 'channel': 'PCAN_USBBUS16', 'interface': 'pcan'}
INFO:root:Connected CAN adapters: [<can.interfaces.pcan.pcan.PcanBus object at 0x0000017DA6DA3490>]
DEBUG:root:CAN adapter: PCAN_USBBUS1
DEBUG:root:BAUD rate: 500000
DEBUG:root:CAN Logging: None
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
Bus error: an error counter reached the 'heavy'/'warning' limit
DEBUG:root:SyncThread was canceled.
DEBUG:root:PeriodicSendThread was canceled.

**Comment by foxBMS** [comment]
Dear @taijisugiyama,

- Have you verified that you receive CAN messages using the tools PEAK System provides, e.g., [PCAN-View](https://www.peak-system.com/PCAN-View.242.0.html)?
- Does the GUI show?

Best regards,
The foxBMS Team

**Comment by taijisugiyama** [comment]
Greetings,
Thank you for your swift reply. I used the PCAN-View and I get the same error. Bus heavy error.

The GUI works and I can start it without a problem. Only when I start doing anything in it, then I get this error.

**Comment by taijisugiyama** [comment]
Also what is by default the baudrate used by master to communicate in CAN?

**Comment by taijisugiyama** [comment]
Initially when I flash the MCU. I receive no CAN messages in PCAN

**Comment by taijisugiyama** [comment]
I have resolved the problem. After looking into the debugger and the code, I found out that I was getting an error flag for the SBC chips. I OTP the SBC chips and now CAN seems to be working. But the PER SBC chip keeps shutting off and on ( I believe because it is not getting sufficient WD?). I have to run the SBC PER in debug mode to be able to use master.

**Comment by foxBMS** [comment]
Dear @taijisugiyama,

we are closing this issue, as it seems that you have found a solution specific to your needs.

Best regards,
The foxBMS Team.
