### ISSUE TITLE
MC33775A Daisy-Chain connection with the MC33664 Interface Card

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#41]
I'm in doubt on how to set-up the connection in hardware for daisy chain with four slave cards (MC33775A). 
1. TPL1 and TPL2 are for multiple chains??
2. TPL1 and TPL2 are working as two ports (TPL1 as TPL_IN or TPL_OUT and TPL2 as TPL_IN or TPL_OUT)?
3. Source code provided in the project uses which concept? TPL1 standalone for bi-directional communication? OR TPL1 is specifically used as TPL_OUT and TPL2 is specifically used for TPL_IN (as in the daisy chain).

Dear foxBMS-2 team, Please suggest me suitable solution which I can use to smoothly connect four of the MC33775A slave cards in daisy chain.

Best Regards,
Bhavay Sen

**Comment by foxBMS** [comment]
Dear @BhavaySen,

TPL1 and TPL2 are for two separate daisy chains.

Best regards,
The foxBMS Team
