### ISSUE TITLE
unable to establish communication with slave MC33775A with the src code given

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#45]
I have set-up the MC33775A based slave card with master. While establishing the communication with the slave, I'm failing to do so. Due to bus activity the slave wakes up and enters in to the deep sleep but could not establish the communication further. Documentation for the respective part in foxBMS-2 Documentation is not completed yet. If anyone faced the same issue or working on the NXP-MC33775A slave please repond.

Looking forward for your responses.

Best Regards,
Bhavay Sen

**Comment by foxBMS** [comment]
Hi @BhavaySen,

There was an issue when communicating with the MC33775A.
This was fixed in foxBMS 2 v1.7.0.

Best regards,
The foxBMS Team
