### ISSUE TITLE
How to select 100 points for the discharge curve of 18650

### ISSUE THREAD

**Issue by FangXS-github** [foxBMS/foxbms-2#46]
src\opt\cells\config\lg_inr18650mj1.c
How to select 100 points for the discharge curve of 18650 `bc_lginr18650mj1SoeLut`?

**Comment by foxBMS** [comment]
Dear @FangXS-github,

Could you please describe your question more specific?

Best regards,
The foxBMS Team

**Comment by FangXS-github** [comment]
how to get the data of array `bc_lginr18650mj1SoeLut` `bc_lginr18650mj1SocLut`?

**Comment by foxBMS** [comment]
Dear @FangXS-github ,

It is out of the scope of this project (development of an open source BMS) to provide answers to general programming questions.

Best regards,
The foxBMS Team
