### ISSUE TITLE
Source files for foxbms-2

### ISSUE THREAD

**Issue by edgaralejod** [foxBMS/foxbms-2#5]
Are you planning on offering the Altium project for the fox BMS 2 Master? The only thing I can find at the moment is a PDF of the schematics.

**Comment by foxBMS** [comment]
Dear @edgaralejod,

 With the foxBMS 2 release [v1.2.0](https://github.com/foxBMS/foxbms-2/releases/tag/v1.2.0) we have published the hardware design files for the BMS-Master Board (version: 1.1.1). These can be found here [hardware/README.md](https://github.com/foxBMS/foxbms-2/blob/master/hardware/README.md).

Best regards,
The foxBMS Team
