### ISSUE TITLE
[QUESTION] Where can I find the software for Slave-BMS?

### ISSUE THREAD

**Issue by vijayuan** [foxBMS/foxbms-2#52]
In src folder, does it just constain Master-BMS software? Where can I find the software for Slave-BMS?

**Comment by foxBMS** [comment]
Dear @vijayuan,

there is no software on the BMS-Slaves, i.e., all software is run on the BMS-Master.
Please have a look at the documentation at https://docs.foxbms.org/.

Best regards,
The foxBMS Team
