### ISSUE TITLE
Hardware before release was tested?? Ethernet PHY is not connected correctly and the slave mc33775a card is not working in default assembly.

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#54]
The data lines for PHY is connected incorrectly i.e. In mirrored manner. 

![ethernet](https://github.com/user-attachments/assets/38b9ab78-77fe-42e5-b6e9-30257d7617ac)

Slave mc33775a is not working in default assembly. Designers of the board calculated the total load requirements from the external series pass regulator?? 

I have an question, whether the **hardware designs are tested before release or not??**

@foxBMS
#47 #44

**Comment by foxBMS** [comment]
Dear @BhavaySen,

please open specific issues for each topic and do not mix different items as this makes tracking issues more complex than needed (e.g., supported AFEs and PHYs are different topics).

- **BMS-Slave**: The MC33775A-based foxBMS BMS-Slave v1.0.0 is working in the default configuration and we cannot reproduce any issue with that hard- or software. If there is an issue with that BMS-Slave please add debug information in #44.
- **BMS-Master**: Thanks for raising the PHY-issue. We will create a specific issue for that bug.

Best regards,
The foxBMS Team
