### ISSUE TITLE
GUI removed. Is there any other way added to see the cell voltages?

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#55]
As in the new release 1.7.0 the gui.bat and gui file is removed. To replace this, any other file had been added to it?? or any other ways to visually check the cell voltages and other BMS data.

@foxBMS

**Comment by foxBMS** [comment]
Dear @BhavaySen,

you can use any available CAN hard- and software to receive the CAN messages from the BMS.
We do not recommend any specific hard- or software.

Best regards,
The foxBMS Team
