### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [foxBMS/foxbms-2#59]
File:
src/app/driver/can/can.c line 532
Code:
 canREG2->IF2MCTL = 0x00001000U | (uint32)0x00000400U | (uint32)0x00000000U /*  identical -->*/ | (uint32)0x00000000U | (uint32)8U;

**Comment by foxBMS** [comment]
Dear @maddin200,

This is intended, please see https://github.com/foxBMS/foxbms-2/issues/17#issuecomment-1689649525.

Best regards,
The foxBMS Team
