### ISSUE TITLE
SOA - Battery Pack Overcurrent

### ISSUE THREAD

**Issue by debangoC** [foxBMS/foxbms-2#6]
Packovercurrent is being checked for Cell Current Limit Violation at line 335 in <soa.c>.
Wouldn't the pack current be much greater than Cell Current Limit.
Also there exists a function for Pack current limit violation however was not able to find the usage for it.

**Comment by foxBMS** [comment]
Dear @debangoC,

thanks for pointing us to that.
This was indeed wrong and we fixed it in the [v1.3.0 release](https://github.com/foxBMS/foxbms-2/releases/tag/v1.3.0) (for details see [soa.c](https://github.com/foxBMS/foxbms-2/blob/2f7d75ed93d75721c1e5210a804323a41bfad947/src/app/application/soa/soa.c#L329)).

Best regards,
The foxBMS Team
