### ISSUE TITLE
CAN ID & Data description

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#64]
Where I can find the document or file of encoded data in CAN messages with the message ID and set of messages and information they carry. 

I'm searching for a document, which I can refer to read the CAN messages and also make a request-response system. 

@foxBMS

**Comment by foxBMS** [comment]
Dear @BhavaySen,

The CAN messages are defined in [tools/dbc](https://github.com/foxBMS/foxbms-2/tree/master/tools/dbc).
This is documented in the general documentation and the README-files that are in most high-level directories.

Best regards,
The foxBMS Team
