### ISSUE TITLE
Master Card Power stabilization and bypassing of SBC PER

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#66]
As per the upcoming revision for 2025 note by @foxBMS . Seems like the master hardware v.1.1.5 is not tested for supply and communication stabilization. 

Is there any way to bypass the PER_SBC and only initialize the MCU_SBC successfully for application operation.

@foxBMS

**Comment by foxBMS** [comment]
Dear @BhavaySen,

The power supply architecture has been streamlined in BMS-Master release v1.2.2 and the peripheral SBC became obsolete (see [iisb-foxbms.iisb.fraunhofer.de/foxbms/gen2/hardware/release/](https://iisb-foxbms.iisb.fraunhofer.de/foxbms/gen2/hardware/release/).

Best regards,
The foxBMS Team
