### ISSUE TITLE
Missing components in BOM

### ISSUE THREAD

**Issue by Shrisha-Balkur** [foxBMS/foxbms-2#7]
Many components in the schematic of the master board [TI TMS570LC4357 Master v1.1.1](https://iisb-foxbms.iisb.fraunhofer.de/foxbms/gen2/hardware/release/master-v1.1.1.zip) are present in the PCB layout but not in the BOM.  

These missing components are cross-marked in the schematics for example: In the buck-boost-converter.SchDoc
![image](https://user-images.githubusercontent.com/67497881/169760671-58c76030-5141-4cb0-8d98-92e90811204d.png)

**Comment by foxBMS** [comment]
Dear @Shrisha-Balkur,

The foxBMS 2 master PCB design includes different component variants (also known as placement options). In the “default” variant, some parts of the schematic are not used and therefore marked with a red cross in the schematic. In the case of the buck-boost-converter the converter is bypassed by placing the resistor R7115, while the remaining components are not soldered to the PCB. The reason for doing this are diverse: The buck-boost converter IC for example is currently not available.

Best regards,
The foxBMS Team
